// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChveemNCVvEvssk1mhDl2A8HXVID1TRQA',
    appId: '1:517757517650:web:60c955e5598dba7ebe048b',
    messagingSenderId: '517757517650',
    projectId: 'semenvitaemanagement',
    authDomain: 'semenvitaemanagement.firebaseapp.com',
    databaseURL: 'https://semenvitaemanagement-default-rtdb.firebaseio.com',
    storageBucket: 'semenvitaemanagement.firebasestorage.app',
    measurementId: 'G-BYPSGSZL9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl-72MyfQYTJqzLMqfh2b-6HGu6CdgIrg',
    appId: '1:517757517650:android:bdc6adeb29d66e39be048b',
    messagingSenderId: '517757517650',
    projectId: 'semenvitaemanagement',
    databaseURL: 'https://semenvitaemanagement-default-rtdb.firebaseio.com',
    storageBucket: 'semenvitaemanagement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy_D0i3PRnDaC7A5MQG8KEOIvc1Ts0iws',
    appId: '1:517757517650:ios:6623af406cfb52dbbe048b',
    messagingSenderId: '517757517650',
    projectId: 'semenvitaemanagement',
    databaseURL: 'https://semenvitaemanagement-default-rtdb.firebaseio.com',
    storageBucket: 'semenvitaemanagement.firebasestorage.app',
    iosBundleId: 'com.example.medicalManagementPwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy_D0i3PRnDaC7A5MQG8KEOIvc1Ts0iws',
    appId: '1:517757517650:ios:6623af406cfb52dbbe048b',
    messagingSenderId: '517757517650',
    projectId: 'semenvitaemanagement',
    databaseURL: 'https://semenvitaemanagement-default-rtdb.firebaseio.com',
    storageBucket: 'semenvitaemanagement.firebasestorage.app',
    iosBundleId: 'com.example.medicalManagementPwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChveemNCVvEvssk1mhDl2A8HXVID1TRQA',
    appId: '1:517757517650:web:e1bb95d3b7295e1bbe048b',
    messagingSenderId: '517757517650',
    projectId: 'semenvitaemanagement',
    authDomain: 'semenvitaemanagement.firebaseapp.com',
    databaseURL: 'https://semenvitaemanagement-default-rtdb.firebaseio.com',
    storageBucket: 'semenvitaemanagement.firebasestorage.app',
    measurementId: 'G-EC8LDZELNY',
  );
}
