// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmqPNJz-fQCi5m8-M8lhBZ-ThzQKXg6aY',
    appId: '1:416627903931:web:498dcb77c9106dc8eb889e',
    messagingSenderId: '416627903931',
    projectId: 'semenvitaemanagement-dev',
    authDomain: 'semenvitaemanagement-dev.firebaseapp.com',
    storageBucket: 'semenvitaemanagement-dev.firebasestorage.app',
    measurementId: 'G-V1P9ELVJJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcPLzHnwWKVmL6ZZIzdAeyfTd58tJzRGU',
    appId: '1:416627903931:android:5a183cfbc7eb2acbeb889e',
    messagingSenderId: '416627903931',
    projectId: 'semenvitaemanagement-dev',
    storageBucket: 'semenvitaemanagement-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkKPewNrwm_B5a0W89vD8K62NfJzYGTgE',
    appId: '1:416627903931:ios:25c0c2a977fe40bdeb889e',
    messagingSenderId: '416627903931',
    projectId: 'semenvitaemanagement-dev',
    storageBucket: 'semenvitaemanagement-dev.firebasestorage.app',
    iosBundleId: 'com.example.medicalManagementPwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkKPewNrwm_B5a0W89vD8K62NfJzYGTgE',
    appId: '1:416627903931:ios:25c0c2a977fe40bdeb889e',
    messagingSenderId: '416627903931',
    projectId: 'semenvitaemanagement-dev',
    storageBucket: 'semenvitaemanagement-dev.firebasestorage.app',
    iosBundleId: 'com.example.medicalManagementPwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmqPNJz-fQCi5m8-M8lhBZ-ThzQKXg6aY',
    appId: '1:416627903931:web:ad36e0f7482507f8eb889e',
    messagingSenderId: '416627903931',
    projectId: 'semenvitaemanagement-dev',
    authDomain: 'semenvitaemanagement-dev.firebaseapp.com',
    storageBucket: 'semenvitaemanagement-dev.firebasestorage.app',
    measurementId: 'G-46F6DMRMSM',
  );
}
